api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "abdelrahman.elewah@gmail.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {} 